In [ ]:
import numpy as np
np.random.seed(0)
data =np.random.randint(0,2,size=(4,4))
data[data==0]=-1
dimen=len(data[0])
picker=np.random.randint(0,dimen,size=2)
print (data)
print(picker)
print(data[picker[0],picker[1]])

[[-1  1  1 -1]
 [ 1  1  1  1]
 [ 1  1  1 -1]
 [-1  1 -1 -1]]
[0 0]
[[-1  1  1 -1]
 [-1  1  1 -1]]


In [93]:
J=1
k_B=1
T=0
energy=1*J

print (np.exp(-energy/(k_B*T)))

ZeroDivisionError: division by zero

In [ ]:
print()

IndexError: index 2 is out of bounds for axis 0 with size 2